version: "3.7"

networks:
  web_network:
    external: true

services:
  traefik:
    image: traefik:1.7.12
    ports:
      - 80:80
      - 443:443
    networks:
      - web_network
    volumes:
      - ./traefik.toml:/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json
      - /tmp:/tmp
    labels:
      - traefik.backend=traefik
      - traefik.docker.network=web_network
      - traefik.frontend.rule=Host:traefik.tristats.lt
      - traefik.enable=true
      - traefik.port=8080
