---
version: '3.7'

networks:
  agent_network:
    external: true
  web_network:
    external: true

volumes:
  portainer_data:
    external: true

services:

  agent:
    image: portainer/agent
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_CLUSTER_ADDR=tasks.agent
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - agent_network
      - web_network
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.backend=portainer"
      - "traefik.docker.network=web_network"
      - "traefik.enable=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:portainer.tristats.lt"
      - "traefik.port=9000"
