version: "3.7"

networks:
  backend_network:
    external: true

volumes:
  postgres_data:
    external: true

services:

  postgres:
    image: postgres:11
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=homer
